/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.model.event;

/**
 *Events generated by the platform
 * 
 */
public enum EventType {
    GENERATE_FX_QUOTE, SAVE_FX_QUOTE
}
